name: Build and Release

# Run this job on all pushes to master with tags with a semantic version
on:
    push:
        tags:
            # normal versions
            - 'v[0-9]+.[0-9]+.[0-9]+'
            # pre-releases
            - 'v[0-9]+.[0-9]+.[0-9]+-**'
jobs:
    # Releases the final docker image to the GHCR
    release:
        # Trigger this step only when a commit is tagged with a version number
        if: |
            github.event_name == 'push' &&
            startsWith(github.ref, 'refs/tags/v')

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Extract the version and commit body from the tag
              id: extract_release
              # The body may be multiline, therefore newlines and % need to be escaped
              run: |
                  VERSION="${{ github.ref }}"
                  VERSION=${VERSION##*/v}
                  echo "::set-output name=VERSION::$VERSION"
      
            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}/maildev-tls
      
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
    
            - name: Log out of GitHub Container Registry
              run: docker logout ghcr.io